# Generated by Django 6.0.4 on 2026-04-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demirbaslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Cihaz Adı')),
                ('tip', models.CharField(choices=[('Laptop', '💻 Laptop'), ('Telefon', '📱 Telefon'), ('Monitor', '🖥️ Monitör'), ('Yazici', '🖨️ Yazıcı'), ('Diger', '🔌 Diğer')], default='Laptop', max_length=20)),
                ('seri_no', models.CharField(max_length=50, unique=True, verbose_name='Seri Numarası')),
                ('ip_adresi', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('rdp_port', models.IntegerField(default=3389, verbose_name='RDP Portu')),
                ('alim_tarihi', models.DateField(blank=True, null=True, verbose_name='Alım Tarihi')),
                ('sahibi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Zimmetli Personel')),
            ],
            options={
                'verbose_name': 'Demirbaş',
                'verbose_name_plural': 'Demirbaşlar',
            },
        ),
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Duyuru Başlığı')),
                ('mesaj', models.TextField(verbose_name='Duyuru İçeriği')),
                ('oncelik', models.CharField(choices=[('Normal', '🔵 Normal Bilgi'), ('Acil', '🔴 Acil Durum'), ('Kutlama', '🟢 Kutlama / Haber')], default='Normal', max_length=20)),
                ('yayinda', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('okuyanlar', models.ManyToManyField(blank=True, related_name='okunan_duyurular', to=settings.AUTH_USER_MODEL, verbose_name='Okuyan Personeller')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Gorevler',
            fields=[
                ('gorev_id', models.AutoField(primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('atayan_personel_id', models.IntegerField(blank=True, null=True)),
                ('gonderen_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Gönderen Maili')),
                ('durum', models.CharField(blank=True, max_length=20, null=True)),
                ('oncelik', models.CharField(blank=True, max_length=20, null=True)),
                ('olusturma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('memnuniyet', models.IntegerField(blank=True, null=True)),
                ('atanan_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='atanan_gorevler', to=settings.AUTH_USER_MODEL)),
                ('cozen_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cozen_gorevler', to=settings.AUTH_USER_MODEL, verbose_name='Görevi Kapatan')),
                ('ilgili_demirbas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yonetim.demirbaslar', verbose_name='İlgili Cihaz')),
            ],
            options={
                'db_table': 'gorevler',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GorevDosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='gorev_dosyalari/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('yukleyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='yonetim.gorevler')),
            ],
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.CharField(max_length=255)),
                ('okundu', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to=settings.AUTH_USER_MODEL)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonetim.gorevler')),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='GorevNotlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notlar', to='yonetim.gorevler')),
                ('yazan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tarih'],
            },
        ),
        migrations.CreateModel(
            name='PersonelProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departman', models.CharField(blank=True, max_length=100, null=True)),
                ('unvan', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='personel_resimleri/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personel Detayı',
                'verbose_name_plural': 'Personel Detayları',
            },
        ),
    ]
