# Generated by Django 6.0.4 on 2026-06-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demirbaslar',
            name='rdp_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RDP Şifresi'),
        ),
        migrations.AddField(
            model_name='demirbaslar',
            name='rdp_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RDP Kullanıcı Adı'),
        ),
    ]
