# Generated by Django 6.0.4 on 2026-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonetim', '0002_demirbaslar_rdp_password_demirbaslar_rdp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='demirbaslar',
            name='vnc_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VNC Şifresi'),
        ),
    ]
